### ISSUE TITLE
请问有一整套的接入方案吗？

### ISSUE THREAD

**Issue by kukudemajia** [phodal/tmall-x1-home-assistant-example#1]
如题，谢谢

**Comment by phodal** [comment]
@kukudemajia 暂时没有。

**Comment by kukudemajia** [comment]
![qq 20171120112447](https://user-images.githubusercontent.com/17118600/33000854-8178a956-cde5-11e7-82de-430c7b93d3ba.jpg)
欢迎入群，都是同好者，相互交流一下
